apiVersion: v1alpha
kind: playwright-cucumberjs
sauce:
  region: eu-central-1
  concurrency: 1
  metadata:
    tags:
      - e2e
    build: "$BUILD_ID"
defaults:
  timeout: 5m
playwright:
  version: 1.39.0
rootDir: ./
suites:
  - name: Cucumber Test
    # The browserName affects the browser metadata of the job as it shows up on the Sauce Labs UI. This value is made available as an environment variable `BROWSER_NAME` on the VM.
    # It's the user's responsibility to launch the correct browser using Playwright,
    # so that the Sauce Labs job metadata matches the actual browser used underneath.
    browserName: chromium
    options:
      paths:
        - "features/**/*.feature"
      require:
        - "step_definitions/*.ts"
      format:
        - "json:my-cucumber.json"
npm:
  dependencies:
    # Following packages are required for running a playwright + cucumber test
    - "@cucumber/cucumber" # cucumber official suggested package
    - "@saucelabs/cucumber-reporter" # Sauce Labs report plugin. Generates a test cases report for display on the Sauce Labs UI.
    - "typescript" # typescript support
    - "ts-node" # typescript support
    # You can append your npm dependencies